[package]
name = "rust_crud_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
mongodb = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2.5"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
futures-util = "0.3"


